export const CategoryList = [
  "Baby Foods",
  "Baked Goods",
  "Baking",
  "Beverages",
  "Canned Goods",
  "Dairy",
  "Deli",
  "Dry Foods",
  "Frozen Foods",
  "Health Care",
  "Household Items",
  "Meat",
  "Personal Care",
  "Produce",
  "Sauces and Condiments",
  "Snacks",
  "Spices and Seasonings",
];
